### ISSUE TITLE
nothing shows in default preset.ini

### ISSUE THREAD

**Issue by ripkoondieeq** [byxor/thug-pro-reshade#1]
![KUREA POMUSZZ!!!!!](https://user-images.githubusercontent.com/100235064/178549107-5bcf140a-52a6-4096-9b7a-10c15bff599f.png) could you help me with this?

**Comment by byxor** [comment]
Strange, I've never seen this happen. Not sure what the problem could be.

**Comment by ripkoondieeq** [comment]
> Strange, I've never seen this happen. Not sure what the problem could be.

nevermind it works fine i had to reinstall all files
