### ISSUE TITLE
effects dont show up lol

### ISSUE THREAD

**Issue by odiplol** [byxor/thug-pro-reshade#3]
![image](https://github.com/byxor/thug-pro-reshade/assets/129446279/7f71a18f-9046-420b-910b-54d2e6ec01dd)
tried reinstalling multiple times

**Comment by byxor** [comment]
Good find. Closing this as a duplicate of #2, but thanks for sharing; it's helpful to know multiple people are seeing the same issue

**Comment by odiplol** [comment]
cool, should of just commented under that post lol.
